from ..exceptions import CompiledPrefabError as CompiledPrefabError

COMPILE_COMMENT: str

def rewrite_code(source: str, *, use_black: bool = ...): ...
def preview(pth, *, use_black: bool = ...): ...
def rewrite_to_py(
    source_path, dest_path, *, header_comment: str = ..., use_black: bool = ...
): ...
def get_sources_to_compare(
    source_path, dest_path, *, header_comment: str = ..., use_black: bool = ...
) -> tuple[str, str]: ...
