from .constants import FIELDS_ATTRIBUTE as FIELDS_ATTRIBUTE
from _collections_abc import Callable as Callable
import typing

def is_prefab(o: typing.Any) -> bool: ...
def is_prefab_instance(o: typing.Any) -> bool: ...
def as_dict(
    inst: object, *, excludes: typing.Union[None, tuple[str, ...]] = ...
) -> dict[str, object]: ...
def to_json(
    inst: object,
    *,
    excludes: typing.Union[None, tuple[str, ...]] = ...,
    dumps_func: typing.Union[None, Callable[..., str]] = ...,
    **kwargs,
) -> str: ...
