from _typeshed import Incomplete
from importlib.machinery import PathFinder, SourceFileLoader

class PrefabHacker(SourceFileLoader):
    def __getattribute__(self, item): ...

    # Pycharm and mypy incorrectly get source_to_code from InspectLoader instead of SourceLoader
    # noinspection PyMethodOverriding
    def source_to_code(self, data, path, *, _optimize: int = ...): ...  # type: ignore
    @staticmethod
    def make_pyc_hash(source_bytes: bytes): ...
    def get_code(self, fullname): ...

class PrefabFinder(PathFinder):
    @classmethod
    def find_spec(
        cls, fullname, path: Incomplete | None = ..., target: Incomplete | None = ...
    ): ...

def insert_prefab_importhook() -> None: ...
def remove_prefab_importhook() -> None: ...

class prefab_compiler:
    def __enter__(self) -> None: ...
    def __exit__(self, exc_type, exc_val, exc_tb) -> None: ...
